#include "angle.h"

#define NULLSDK_MAKE_ANGLE_FUNCTION(type, name, body) type angle_t<type>::name##() const { return body; }

#define NULLSDK_MAKE_DEGREES_FUNCTUIN(name) NULLSDK_MAKE_ANGLE_FUNCTION(degrees_t, name, std::name##(cast()) * angle_t<radians_t>::pi)
#define NULLSDK_MAKE_RADIANS_FUNCTUIN(name) NULLSDK_MAKE_ANGLE_FUNCTION(radians_t, name, std::name##(angle))

#define NULLSDK_MAKE_ANGLE_FUNCTIONS(type, name) type(name) type(a##name) type(name##h) type(a##name##h)

NULLSDK_MAKE_ANGLE_FUNCTIONS(NULLSDK_MAKE_DEGREES_FUNCTUIN, sin);
NULLSDK_MAKE_ANGLE_FUNCTIONS(NULLSDK_MAKE_DEGREES_FUNCTUIN, cos);
NULLSDK_MAKE_ANGLE_FUNCTIONS(NULLSDK_MAKE_DEGREES_FUNCTUIN, tan);

NULLSDK_MAKE_ANGLE_FUNCTIONS(NULLSDK_MAKE_RADIANS_FUNCTUIN, sin);
NULLSDK_MAKE_ANGLE_FUNCTIONS(NULLSDK_MAKE_RADIANS_FUNCTUIN, cos);
NULLSDK_MAKE_ANGLE_FUNCTIONS(NULLSDK_MAKE_RADIANS_FUNCTUIN, tan);